#requires -Version 5.1

[CmdletBinding()]
param(
    [string]$RepositoryRoot = "",
    [switch]$Check
)

$ErrorActionPreference = "Stop"

if ([string]::IsNullOrWhiteSpace($RepositoryRoot)) {
    $RepositoryRoot = Join-Path $PSScriptRoot "..\.."
}
$RepositoryRoot = [System.IO.Path]::GetFullPath($RepositoryRoot)
$webRoot = Join-Path $RepositoryRoot "vSMR\src\control_center\web"
$bundlePath = Join-Path $webRoot "app-bundle.js"
$sourceNames = @(
    "app-model.js",
    "app-workflow.js",
    "app-runtime.js",
    "app-profile-colors.js",
    "app-profile-editor.js",
    "app-aviso-editor.js",
    "app-settings.js",
    "app-persistence.js",
    "app-events.js",
    "app-actions.js",
    "app.js"
)

$builder = [System.Text.StringBuilder]::new()
[void]$builder.AppendLine("// Generated by vSMR/tools/build_control_center_bundle.ps1. Do not edit directly.")
[void]$builder.AppendLine("(function () {")
[void]$builder.AppendLine('"use strict";')
foreach ($sourceName in $sourceNames) {
    $sourcePath = Join-Path $webRoot $sourceName
    if (-not (Test-Path -LiteralPath $sourcePath -PathType Leaf)) {
        throw "Control Center source '$sourcePath' was not found."
    }
    [void]$builder.AppendLine("")
    [void]$builder.AppendLine("// source: $sourceName")
    $source = [System.IO.File]::ReadAllText($sourcePath)
    [void]$builder.Append($source.TrimEnd("`r", "`n"))
    [void]$builder.AppendLine("")
}
[void]$builder.AppendLine("")
[void]$builder.AppendLine("})();")

$expected = $builder.ToString().Replace("`r`n", "`n")
$actual = if (Test-Path -LiteralPath $bundlePath -PathType Leaf) {
    [System.IO.File]::ReadAllText($bundlePath).Replace("`r`n", "`n")
} else {
    ""
}

if ($Check) {
    if ($actual -cne $expected) {
        Write-Error "Control Center bundle is missing or stale: $bundlePath"
        exit 1
    }
    Write-Host "Control Center bundle is current."
    exit 0
}

$utf8WithoutBom = [System.Text.UTF8Encoding]::new($false)
[System.IO.File]::WriteAllText($bundlePath, $expected, $utf8WithoutBom)
Write-Host "Generated $bundlePath"
