#requires -Version 5.1

[CmdletBinding()]
param(
    [string]$RepositoryRoot = "",
    [switch]$Check
)

$ErrorActionPreference = "Stop"

if ([string]::IsNullOrWhiteSpace($RepositoryRoot)) {
    $RepositoryRoot = Join-Path $PSScriptRoot "..\.."
}
$RepositoryRoot = [System.IO.Path]::GetFullPath($RepositoryRoot)
$webRoot = Join-Path $RepositoryRoot "vSMR\src\control_center\web"
$sourceRoot = Join-Path $webRoot "styles"
$bundlePath = Join-Path $webRoot "styles.css"
$manifestPath = Join-Path $sourceRoot "sources.txt"
if (-not (Test-Path -LiteralPath $manifestPath -PathType Leaf)) {
    throw "Control Center stylesheet manifest '$manifestPath' was not found."
}
$sourceNames = @(
    [IO.File]::ReadAllLines($manifestPath) |
        ForEach-Object { $_.Trim() } |
        Where-Object { $_ -and -not $_.StartsWith('#') }
)
if ($sourceNames.Count -eq 0 -or ($sourceNames | Select-Object -Unique).Count -ne $sourceNames.Count) {
    throw "Control Center stylesheet manifest must contain a non-empty, unique source list."
}
foreach ($sourceName in $sourceNames) {
    if ([IO.Path]::GetFileName($sourceName) -cne $sourceName -or
        [IO.Path]::GetExtension($sourceName) -cne '.css') {
        throw "Invalid Control Center stylesheet manifest entry '$sourceName'."
    }
}

$builder = [System.Text.StringBuilder]::new()
[void]$builder.AppendLine("/* Generated by vSMR/tools/build_control_center_styles.ps1. Do not edit directly. */")
foreach ($sourceName in $sourceNames) {
    $sourcePath = Join-Path $sourceRoot $sourceName
    if (-not (Test-Path -LiteralPath $sourcePath -PathType Leaf)) {
        throw "Control Center style source '$sourcePath' was not found."
    }
    [void]$builder.AppendLine("")
    [void]$builder.AppendLine("/* source: $sourceName */")
    $source = [System.IO.File]::ReadAllText($sourcePath)
    [void]$builder.Append($source.TrimEnd("`r", "`n"))
    [void]$builder.AppendLine("")
}

$expected = $builder.ToString().Replace("`r`n", "`n")
$actual = if (Test-Path -LiteralPath $bundlePath -PathType Leaf) {
    [System.IO.File]::ReadAllText($bundlePath).Replace("`r`n", "`n")
} else {
    ""
}

if ($Check) {
    if ($actual -cne $expected) {
        Write-Error "Control Center stylesheet bundle is missing or stale: $bundlePath"
        exit 1
    }
    Write-Host "Control Center stylesheet bundle is current."
    exit 0
}

$utf8WithoutBom = [System.Text.UTF8Encoding]::new($false)
[System.IO.File]::WriteAllText($bundlePath, $expected, $utf8WithoutBom)
Write-Host "Generated $bundlePath"
