# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.5.{build}

# branches to build
branches:
  # whitelist
  only:
    - main
    - master
    - dev

  # blacklist
  except:
    - gh-pages

# Maximum number of concurrent jobs for the project
max_jobs: 1

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2022

#---------------------------------#
#       build configuration       #
#---------------------------------#

install:
  - cmd: msbuild /version

# build Configuration, i.e. Debug, Release, etc.
configuration: Release
platform: Win32

build_script:
  - cmd: msbuild "C:\projects\vsmr\vSMR.sln" /t:Restore /p:Configuration=Release /p:Platform=Win32
  - cmd: msbuild "C:\projects\vsmr\vSMR.sln" /m /p:Configuration=Release /p:Platform=Win32 /p:PlatformToolset=v143 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
  - cmd: mkdir vSMR-nightly
  - cmd: copy /Y Release\vSMR.dll vSMR-nightly\
  - cmd: xcopy Release\vSMR_Data vSMR-nightly\vSMR_Data\ /E /I /Y
  - cmd: 7z a vSMR-nightly.zip %APPVEYOR_BUILD_FOLDER%\vSMR-nightly\

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: vSMR-nightly.zip
